/* eslint-disable no-unused-vars */
/* eslint-disable no-undef */
$(function () {
  const stateSelect = document.getElementById("state");
  states.forEach(function (state) {
    const option = document.createElement("option");
    option.value = state.abbreviation;
    option.text = state.name;
    stateSelect.appendChild(option);
  });

  $("#department").selectmenu();
  $("#state").selectmenu();

  $("#date-of-birth").datetimepicker({
    timepicker: false,
    format: "m/d/Y",
  });
  $("#start-date").datetimepicker({
    timepicker: false,
    format: "m/d/Y",
  });
});

function saveEmployee() {
  const firstName = document.getElementById("first-name");
  const lastName = document.getElementById("last-name");
  const dateOfBirth = document.getElementById("date-of-birth");
  const startDate = document.getElementById("start-date");
  const department = document.getElementById("department");
  const street = document.getElementById("street");
  const city = document.getElementById("city");
  const state = document.getElementById("state");
  const zipCode = document.getElementById("zip-code");

  const employees =
    JSON.parse(localStorage.getItem("employees")) || initialEmployeeList;
  const employee = {
    firstName: firstName.value,
    lastName: lastName.value,
    dateOfBirth: dateOfBirth.value,
    startDate: startDate.value,
    department: department.value,
    street: street.value,
    city: city.value,
    state: state.value,
    zipCode: zipCode.value,
  };
  employees.push(employee);
  localStorage.setItem("employees", JSON.stringify(employees));
  $("#confirmation").modal();
}

const states = [
  {
    name: "Alabama",
    abbreviation: "AL",
  },
  {
    name: "Alaska",
    abbreviation: "AK",
  },
  {
    name: "American Samoa",
    abbreviation: "AS",
  },
  {
    name: "Arizona",
    abbreviation: "AZ",
  },
  {
    name: "Arkansas",
    abbreviation: "AR",
  },
  {
    name: "California",
    abbreviation: "CA",
  },
  {
    name: "Colorado",
    abbreviation: "CO",
  },
  {
    name: "Connecticut",
    abbreviation: "CT",
  },
  {
    name: "Delaware",
    abbreviation: "DE",
  },
  {
    name: "District Of Columbia",
    abbreviation: "DC",
  },
  {
    name: "Federated States Of Micronesia",
    abbreviation: "FM",
  },
  {
    name: "Florida",
    abbreviation: "FL",
  },
  {
    name: "Georgia",
    abbreviation: "GA",
  },
  {
    name: "Guam",
    abbreviation: "GU",
  },
  {
    name: "Hawaii",
    abbreviation: "HI",
  },
  {
    name: "Idaho",
    abbreviation: "ID",
  },
  {
    name: "Illinois",
    abbreviation: "IL",
  },
  {
    name: "Indiana",
    abbreviation: "IN",
  },
  {
    name: "Iowa",
    abbreviation: "IA",
  },
  {
    name: "Kansas",
    abbreviation: "KS",
  },
  {
    name: "Kentucky",
    abbreviation: "KY",
  },
  {
    name: "Louisiana",
    abbreviation: "LA",
  },
  {
    name: "Maine",
    abbreviation: "ME",
  },
  {
    name: "Marshall Islands",
    abbreviation: "MH",
  },
  {
    name: "Maryland",
    abbreviation: "MD",
  },
  {
    name: "Massachusetts",
    abbreviation: "MA",
  },
  {
    name: "Michigan",
    abbreviation: "MI",
  },
  {
    name: "Minnesota",
    abbreviation: "MN",
  },
  {
    name: "Mississippi",
    abbreviation: "MS",
  },
  {
    name: "Missouri",
    abbreviation: "MO",
  },
  {
    name: "Montana",
    abbreviation: "MT",
  },
  {
    name: "Nebraska",
    abbreviation: "NE",
  },
  {
    name: "Nevada",
    abbreviation: "NV",
  },
  {
    name: "New Hampshire",
    abbreviation: "NH",
  },
  {
    name: "New Jersey",
    abbreviation: "NJ",
  },
  {
    name: "New Mexico",
    abbreviation: "NM",
  },
  {
    name: "New York",
    abbreviation: "NY",
  },
  {
    name: "North Carolina",
    abbreviation: "NC",
  },
  {
    name: "North Dakota",
    abbreviation: "ND",
  },
  {
    name: "Northern Mariana Islands",
    abbreviation: "MP",
  },
  {
    name: "Ohio",
    abbreviation: "OH",
  },
  {
    name: "Oklahoma",
    abbreviation: "OK",
  },
  {
    name: "Oregon",
    abbreviation: "OR",
  },
  {
    name: "Palau",
    abbreviation: "PW",
  },
  {
    name: "Pennsylvania",
    abbreviation: "PA",
  },
  {
    name: "Puerto Rico",
    abbreviation: "PR",
  },
  {
    name: "Rhode Island",
    abbreviation: "RI",
  },
  {
    name: "South Carolina",
    abbreviation: "SC",
  },
  {
    name: "South Dakota",
    abbreviation: "SD",
  },
  {
    name: "Tennessee",
    abbreviation: "TN",
  },
  {
    name: "Texas",
    abbreviation: "TX",
  },
  {
    name: "Utah",
    abbreviation: "UT",
  },
  {
    name: "Vermont",
    abbreviation: "VT",
  },
  {
    name: "Virgin Islands",
    abbreviation: "VI",
  },
  {
    name: "Virginia",
    abbreviation: "VA",
  },
  {
    name: "Washington",
    abbreviation: "WA",
  },
  {
    name: "West Virginia",
    abbreviation: "WV",
  },
  {
    name: "Wisconsin",
    abbreviation: "WI",
  },
  {
    name: "Wyoming",
    abbreviation: "WY",
  },
];

const initialEmployeeList = [
  {
    firstName: "Terza",
    lastName: "Marley",
    dateOfBirth: "13/10/1987",
    startDate: "6/8/2003",
    street: "300 Superior Crossing",
    city: "Saint Joseph",
    zipCode: "64504",
    state: "MO",
    department: "Engineering",
  },
  {
    firstName: "Derick",
    lastName: "Moss",
    dateOfBirth: "14/11/1986",
    startDate: "11/6/2006",
    street: "0 Lunder Drive",
    city: "Waterbury",
    zipCode: "06726",
    state: "CT",
    department: "Engineering",
  },
  {
    firstName: "Barron",
    lastName: "Knell",
    dateOfBirth: "17/6/1959",
    startDate: "20/1/2002",
    street: "769 Jay Drive",
    city: "Philadelphia",
    zipCode: "19196",
    state: "PA",
    department: "Legal",
  },
  {
    firstName: "Cullin",
    lastName: "Halford",
    dateOfBirth: "21/11/1992",
    startDate: "27/11/2020",
    street: "14532 Dapin Plaza",
    city: "Torrance",
    zipCode: "90505",
    state: "CA",
    department: "Human Resources",
  },
  {
    firstName: "Maryl",
    lastName: "McKew",
    dateOfBirth: "16/9/2000",
    startDate: "25/8/2001",
    street: "79 Toban Park",
    city: "Evansville",
    zipCode: "47732",
    state: "IN",
    department: "Engineering",
  },
  {
    firstName: "Maire",
    lastName: "McMarquis",
    dateOfBirth: "3/7/1994",
    startDate: "6/9/2010",
    street: "8512 Schiller Hill",
    city: "Charlotte",
    zipCode: "28235",
    state: "NC",
    department: "Engineering",
  },
  {
    firstName: "Giordano",
    lastName: "Englishby",
    dateOfBirth: "8/8/1989",
    startDate: "4/9/2008",
    street: "7 Delaware Junction",
    city: "Miami Beach",
    zipCode: "33141",
    state: "FL",
    department: "Legal",
  },
  {
    firstName: "Brandea",
    lastName: "Swiffen",
    dateOfBirth: "21/6/1999",
    startDate: "4/2/2021",
    street: "67188 Morrow Alley",
    city: "Sacramento",
    zipCode: "95865",
    state: "CA",
    department: "Human Resources",
  },
  {
    firstName: "Lesya",
    lastName: "Itskovitz",
    dateOfBirth: "2/1/1998",
    startDate: "17/4/2014",
    street: "57342 Scott Terrace",
    city: "Tucson",
    zipCode: "85743",
    state: "AZ",
    department: "Human Resources",
  },
  {
    firstName: "Lavina",
    lastName: "Chalcroft",
    dateOfBirth: "8/10/1973",
    startDate: "19/5/2004",
    street: "5 Hoffman Place",
    city: "Fort Lauderdale",
    zipCode: "33320",
    state: "FL",
    department: "Human Resources",
  },
  {
    firstName: "Paddy",
    lastName: "Hassen",
    dateOfBirth: "29/9/1974",
    startDate: "28/7/2010",
    street: "4 Oak Park",
    city: "Washington",
    zipCode: "20591",
    state: "DC",
    department: "Engineering",
  },
  {
    firstName: "Garland",
    lastName: "Morling",
    dateOfBirth: "21/11/1978",
    startDate: "1/1/2012",
    street: "5 Ryan Lane",
    city: "Washington",
    zipCode: "20442",
    state: "DC",
    department: "Legal",
  },
  {
    firstName: "Nichol",
    lastName: "Floris",
    dateOfBirth: "14/1/1977",
    startDate: "16/8/2022",
    street: "77 Springs Road",
    city: "Camden",
    zipCode: "08104",
    state: "NJ",
    department: "Legal",
  },
  {
    firstName: "Theodore",
    lastName: "Di Giacomo",
    dateOfBirth: "6/12/1966",
    startDate: "9/3/2012",
    street: "2 Buell Street",
    city: "Dallas",
    zipCode: "75323",
    state: "TX",
    department: "Sales",
  },
  {
    firstName: "Rolland",
    lastName: "Loyd",
    dateOfBirth: "1/6/1971",
    startDate: "23/9/2007",
    street: "44283 Stang Place",
    city: "Detroit",
    zipCode: "48232",
    state: "MI",
    department: "Engineering",
  },
  {
    firstName: "Bartie",
    lastName: "Follen",
    dateOfBirth: "17/8/1964",
    startDate: "17/9/2015",
    street: "8 Algoma Road",
    city: "Charlotte",
    zipCode: "28284",
    state: "NC",
    department: "Human Resources",
  },
  {
    firstName: "Mindy",
    lastName: "Joanaud",
    dateOfBirth: "27/8/1993",
    startDate: "9/7/2008",
    street: "841 Sullivan Avenue",
    city: "Fort Smith",
    zipCode: "72916",
    state: "AR",
    department: "Sales",
  },
  {
    firstName: "Milka",
    lastName: "Crich",
    dateOfBirth: "3/10/1978",
    startDate: "12/6/2008",
    street: "06698 Esker Junction",
    city: "San Jose",
    zipCode: "95108",
    state: "CA",
    department: "Sales",
  },
  {
    firstName: "Lesley",
    lastName: "Sparkwill",
    dateOfBirth: "15/6/1977",
    startDate: "26/10/2020",
    street: "18594 Prairie Rose Drive",
    city: "San Diego",
    zipCode: "92160",
    state: "CA",
    department: "Human Resources",
  },
  {
    firstName: "Tawsha",
    lastName: "Jacquemy",
    dateOfBirth: "3/3/1965",
    startDate: "3/4/2009",
    street: "9 Nevada Hill",
    city: "Erie",
    zipCode: "16505",
    state: "PA",
    department: "Marketing",
  },
  {
    firstName: "Patrick",
    lastName: "Tremmil",
    dateOfBirth: "2/10/1980",
    startDate: "3/10/2006",
    street: "3999 Grayhawk Trail",
    city: "Norcross",
    zipCode: "30092",
    state: "GA",
    department: "Legal",
  },
  {
    firstName: "Tommie",
    lastName: "Lentsch",
    dateOfBirth: "3/2/1969",
    startDate: "3/6/2014",
    street: "782 Dennis Court",
    city: "Phoenix",
    zipCode: "85099",
    state: "AZ",
    department: "Marketing",
  },
  {
    firstName: "Mikkel",
    lastName: "Ledgerton",
    dateOfBirth: "19/11/1965",
    startDate: "17/5/2017",
    street: "4 Bellgrove Street",
    city: "Lexington",
    zipCode: "40505",
    state: "KY",
    department: "Engineering",
  },
  {
    firstName: "Kelci",
    lastName: "Bardnam",
    dateOfBirth: "29/11/1989",
    startDate: "9/5/2016",
    street: "6 Hauk Parkway",
    city: "Birmingham",
    zipCode: "35295",
    state: "AL",
    department: "Human Resources",
  },
  {
    firstName: "Morgana",
    lastName: "Beiderbeck",
    dateOfBirth: "10/9/1969",
    startDate: "10/1/2018",
    street: "99 Caliangt Drive",
    city: "Akron",
    zipCode: "44329",
    state: "OH",
    department: "Human Resources",
  },
  {
    firstName: "Spike",
    lastName: "Adamiak",
    dateOfBirth: "29/9/1987",
    startDate: "2/4/2003",
    street: "71 Spenser Court",
    city: "San Diego",
    zipCode: "92105",
    state: "CA",
    department: "Engineering",
  },
  {
    firstName: "Arleen",
    lastName: "Ajam",
    dateOfBirth: "7/7/1991",
    startDate: "2/9/2015",
    street: "9853 Corry Way",
    city: "Huntsville",
    zipCode: "35895",
    state: "AL",
    department: "Sales",
  },
  {
    firstName: "Teirtza",
    lastName: "MacAleese",
    dateOfBirth: "17/9/1979",
    startDate: "9/10/2022",
    street: "09 Forest Dale Park",
    city: "Santa Monica",
    zipCode: "90410",
    state: "CA",
    department: "Sales",
  },
  {
    firstName: "Anetta",
    lastName: "Bownass",
    dateOfBirth: "4/6/1992",
    startDate: "16/2/2019",
    street: "26 Sheridan Pass",
    city: "Missoula",
    zipCode: "59806",
    state: "MT",
    department: "Sales",
  },
  {
    firstName: "Stephani",
    lastName: "Renzullo",
    dateOfBirth: "8/3/1960",
    startDate: "10/1/2017",
    street: "75384 Talmadge Plaza",
    city: "El Paso",
    zipCode: "88553",
    state: "TX",
    department: "Human Resources",
  },
  {
    firstName: "Brandi",
    lastName: "Yanyshev",
    dateOfBirth: "23/6/1981",
    startDate: "11/1/2000",
    street: "12 Troy Road",
    city: "Springfield",
    zipCode: "65810",
    state: "MO",
    department: "Legal",
  },
  {
    firstName: "Dominica",
    lastName: "Seide",
    dateOfBirth: "2/12/1998",
    startDate: "24/10/2009",
    street: "92 Crescent Oaks Drive",
    city: "New Orleans",
    zipCode: "70165",
    state: "LA",
    department: "Legal",
  },
  {
    firstName: "Ellsworth",
    lastName: "Carvill",
    dateOfBirth: "20/2/1967",
    startDate: "30/11/2001",
    street: "20650 Darwin Trail",
    city: "Evansville",
    zipCode: "47747",
    state: "IN",
    department: "Sales",
  },
  {
    firstName: "Morgen",
    lastName: "Wilgar",
    dateOfBirth: "15/7/1977",
    startDate: "1/7/2017",
    street: "407 Erie Road",
    city: "Garland",
    zipCode: "75044",
    state: "TX",
    department: "Legal",
  },
  {
    firstName: "Melisande",
    lastName: "Jaffra",
    dateOfBirth: "27/7/1963",
    startDate: "24/1/2020",
    street: "1371 Mitchell Crossing",
    city: "Denver",
    zipCode: "80262",
    state: "CO",
    department: "Human Resources",
  },
  {
    firstName: "Lambert",
    lastName: "Bazylets",
    dateOfBirth: "16/8/1961",
    startDate: "8/4/2017",
    street: "46 Kipling Street",
    city: "Los Angeles",
    zipCode: "90189",
    state: "CA",
    department: "Human Resources",
  },
  {
    firstName: "Caleb",
    lastName: "Woodbridge",
    dateOfBirth: "8/1/1961",
    startDate: "27/5/2017",
    street: "257 Randy Place",
    city: "Jacksonville",
    zipCode: "32255",
    state: "FL",
    department: "Marketing",
  },
  {
    firstName: "Martita",
    lastName: "Botright",
    dateOfBirth: "23/1/1978",
    startDate: "12/6/2021",
    street: "1 Reinke Terrace",
    city: "Des Moines",
    zipCode: "50310",
    state: "IA",
    department: "Human Resources",
  },
  {
    firstName: "Cassie",
    lastName: "Fellibrand",
    dateOfBirth: "5/7/1984",
    startDate: "23/6/2017",
    street: "48958 Carey Terrace",
    city: "Bridgeport",
    zipCode: "06606",
    state: "CT",
    department: "Sales",
  },
  {
    firstName: "Em",
    lastName: "Propper",
    dateOfBirth: "5/12/1979",
    startDate: "5/3/2021",
    street: "1 Del Sol Road",
    city: "Springfield",
    zipCode: "62764",
    state: "IL",
    department: "Sales",
  },
  {
    firstName: "Valentine",
    lastName: "Lagne",
    dateOfBirth: "15/5/1975",
    startDate: "4/6/2007",
    street: "92 Gina Park",
    city: "Huntington Beach",
    zipCode: "92648",
    state: "CA",
    department: "Human Resources",
  },
  {
    firstName: "Marylou",
    lastName: "Gaye",
    dateOfBirth: "13/9/1961",
    startDate: "18/6/2003",
    street: "314 Thompson Parkway",
    city: "Madison",
    zipCode: "53726",
    state: "WI",
    department: "Sales",
  },
  {
    firstName: "Amandy",
    lastName: "Gorse",
    dateOfBirth: "26/11/1961",
    startDate: "4/3/2015",
    street: "2 Dawn Street",
    city: "San Antonio",
    zipCode: "78210",
    state: "TX",
    department: "Human Resources",
  },
  {
    firstName: "Rufus",
    lastName: "Mossdale",
    dateOfBirth: "6/12/1962",
    startDate: "30/5/2014",
    street: "18 Towne Point",
    city: "Minneapolis",
    zipCode: "55446",
    state: "MN",
    department: "Marketing",
  },
  {
    firstName: "Christiano",
    lastName: "Bensley",
    dateOfBirth: "28/1/1979",
    startDate: "16/5/2005",
    street: "2149 Esch Alley",
    city: "Atlanta",
    zipCode: "30343",
    state: "GA",
    department: "Legal",
  },
  {
    firstName: "Emmalyn",
    lastName: "Kinig",
    dateOfBirth: "4/2/1990",
    startDate: "29/12/2010",
    street: "602 Barby Avenue",
    city: "Pasadena",
    zipCode: "91186",
    state: "CA",
    department: "Marketing",
  },
  {
    firstName: "Donn",
    lastName: "Storey",
    dateOfBirth: "26/10/1957",
    startDate: "2/6/2019",
    street: "11 Goodland Terrace",
    city: "Los Angeles",
    zipCode: "90015",
    state: "CA",
    department: "Legal",
  },
  {
    firstName: "Josephine",
    lastName: "Gentle",
    dateOfBirth: "12/2/1992",
    startDate: "29/6/2019",
    street: "457 Almo Crossing",
    city: "Peoria",
    zipCode: "61656",
    state: "IL",
    department: "Sales",
  },
  {
    firstName: "Pammie",
    lastName: "Calderwood",
    dateOfBirth: "24/2/1951",
    startDate: "18/9/2004",
    street: "5494 Basil Road",
    city: "San Francisco",
    zipCode: "94169",
    state: "CA",
    department: "Engineering",
  },
  {
    firstName: "Rita",
    lastName: "Eadington",
    dateOfBirth: "31/10/1994",
    startDate: "2/9/2015",
    street: "6 Rowland Avenue",
    city: "Daytona Beach",
    zipCode: "32123",
    state: "FL",
    department: "Human Resources",
  },
  {
    firstName: "Maryanne",
    lastName: "Androlli",
    dateOfBirth: "22/9/1952",
    startDate: "7/3/2020",
    street: "9026 Eagle Crest Center",
    city: "Houston",
    zipCode: "77040",
    state: "TX",
    department: "Human Resources",
  },
  {
    firstName: "Jonah",
    lastName: "Etteridge",
    dateOfBirth: "14/2/1955",
    startDate: "28/7/2017",
    street: "7944 Starling Junction",
    city: "Rochester",
    zipCode: "14646",
    state: "NY",
    department: "Engineering",
  },
  {
    firstName: "Jerad",
    lastName: "Gutowski",
    dateOfBirth: "23/11/1967",
    startDate: "27/5/2020",
    street: "7375 Grim Center",
    city: "West Palm Beach",
    zipCode: "33411",
    state: "FL",
    department: "Engineering",
  },
  {
    firstName: "Selena",
    lastName: "Shorthill",
    dateOfBirth: "28/4/1979",
    startDate: "11/9/2000",
    street: "666 Karstens Plaza",
    city: "Richmond",
    zipCode: "23228",
    state: "VA",
    department: "Marketing",
  },
  {
    firstName: "Bradford",
    lastName: "Gladtbach",
    dateOfBirth: "25/9/1953",
    startDate: "13/10/2006",
    street: "98 Meadow Ridge Street",
    city: "Mount Vernon",
    zipCode: "10557",
    state: "NY",
    department: "Engineering",
  },
  {
    firstName: "Haven",
    lastName: "Massenhove",
    dateOfBirth: "18/9/1996",
    startDate: "30/7/2010",
    street: "4 Cordelia Terrace",
    city: "Augusta",
    zipCode: "30911",
    state: "GA",
    department: "Marketing",
  },
  {
    firstName: "Bancroft",
    lastName: "Blowfield",
    dateOfBirth: "17/5/1965",
    startDate: "18/9/2011",
    street: "02967 Walton Parkway",
    city: "Schenectady",
    zipCode: "12325",
    state: "NY",
    department: "Engineering",
  },
  {
    firstName: "Robert",
    lastName: "Hallgalley",
    dateOfBirth: "15/8/1956",
    startDate: "12/10/2000",
    street: "53 Westend Road",
    city: "Akron",
    zipCode: "44305",
    state: "OH",
    department: "Human Resources",
  },
  {
    firstName: "Carolina",
    lastName: "Elsegood",
    dateOfBirth: "30/4/1969",
    startDate: "11/5/2000",
    street: "87213 Oriole Circle",
    city: "Louisville",
    zipCode: "40225",
    state: "KY",
    department: "Human Resources",
  },
  {
    firstName: "Guenna",
    lastName: "Witton",
    dateOfBirth: "28/4/1991",
    startDate: "2/4/2016",
    street: "212 Green Ridge Street",
    city: "Grand Forks",
    zipCode: "58207",
    state: "ND",
    department: "Sales",
  },
  {
    firstName: "Concettina",
    lastName: "Ruegg",
    dateOfBirth: "29/8/1963",
    startDate: "11/3/2020",
    street: "2722 Melby Lane",
    city: "Washington",
    zipCode: "20051",
    state: "DC",
    department: "Human Resources",
  },
  {
    firstName: "Lucho",
    lastName: "Lobb",
    dateOfBirth: "26/3/1985",
    startDate: "25/5/2002",
    street: "39730 Florence Alley",
    city: "Grand Rapids",
    zipCode: "49518",
    state: "MI",
    department: "Legal",
  },
  {
    firstName: "Minny",
    lastName: "Glen",
    dateOfBirth: "13/9/1971",
    startDate: "3/8/2016",
    street: "13509 Crownhardt Park",
    city: "Santa Clara",
    zipCode: "95054",
    state: "CA",
    department: "Engineering",
  },
  {
    firstName: "Berget",
    lastName: "Guppey",
    dateOfBirth: "29/6/1973",
    startDate: "19/2/2003",
    street: "29891 Bowman Way",
    city: "San Francisco",
    zipCode: "94154",
    state: "CA",
    department: "Legal",
  },
  {
    firstName: "Ashli",
    lastName: "Dykins",
    dateOfBirth: "6/8/1993",
    startDate: "11/4/2011",
    street: "84 Mallard Parkway",
    city: "Worcester",
    zipCode: "01654",
    state: "MA",
    department: "Human Resources",
  },
  {
    firstName: "Angelico",
    lastName: "Kempstone",
    dateOfBirth: "28/2/1954",
    startDate: "4/3/2007",
    street: "62288 Huxley Park",
    city: "Houston",
    zipCode: "77255",
    state: "TX",
    department: "Marketing",
  },
  {
    firstName: "Hartley",
    lastName: "Benito",
    dateOfBirth: "23/1/1967",
    startDate: "3/4/2005",
    street: "92304 Commercial Trail",
    city: "Springfield",
    zipCode: "65810",
    state: "MO",
    department: "Legal",
  },
  {
    firstName: "Koren",
    lastName: "Rubens",
    dateOfBirth: "8/12/1959",
    startDate: "28/7/2008",
    street: "67 Nancy Lane",
    city: "Canton",
    zipCode: "44710",
    state: "OH",
    department: "Marketing",
  },
  {
    firstName: "Mar",
    lastName: "Conyers",
    dateOfBirth: "31/8/1981",
    startDate: "20/11/2019",
    street: "789 Arizona Crossing",
    city: "Lexington",
    zipCode: "40586",
    state: "KY",
    department: "Engineering",
  },
  {
    firstName: "Desmond",
    lastName: "Puckrin",
    dateOfBirth: "16/10/1980",
    startDate: "10/7/2004",
    street: "8698 Banding Terrace",
    city: "San Francisco",
    zipCode: "94132",
    state: "CA",
    department: "Engineering",
  },
  {
    firstName: "Nickolaus",
    lastName: "Manuel",
    dateOfBirth: "20/6/1997",
    startDate: "29/10/2004",
    street: "599 Ridgeview Plaza",
    city: "Jeffersonville",
    zipCode: "47134",
    state: "IN",
    department: "Legal",
  },
  {
    firstName: "Blinni",
    lastName: "Spoole",
    dateOfBirth: "26/9/1997",
    startDate: "3/3/2016",
    street: "62 Haas Place",
    city: "Chattanooga",
    zipCode: "37450",
    state: "TN",
    department: "Engineering",
  },
  {
    firstName: "Clarisse",
    lastName: "O'Feeney",
    dateOfBirth: "27/12/1986",
    startDate: "19/3/2005",
    street: "383 Saint Paul Pass",
    city: "Las Vegas",
    zipCode: "89145",
    state: "NV",
    department: "Human Resources",
  },
  {
    firstName: "Ethelyn",
    lastName: "Offen",
    dateOfBirth: "17/3/1950",
    startDate: "20/2/2004",
    street: "5 Eagan Drive",
    city: "Trenton",
    zipCode: "08608",
    state: "NJ",
    department: "Human Resources",
  },
  {
    firstName: "Jackquelin",
    lastName: "Staddon",
    dateOfBirth: "10/1/1967",
    startDate: "2/8/2017",
    street: "81852 Barnett Crossing",
    city: "Charlotte",
    zipCode: "28205",
    state: "NC",
    department: "Legal",
  },
  {
    firstName: "Morly",
    lastName: "Trenbay",
    dateOfBirth: "2/5/1998",
    startDate: "15/2/2004",
    street: "3259 Sage Alley",
    city: "Buffalo",
    zipCode: "14233",
    state: "NY",
    department: "Marketing",
  },
  {
    firstName: "Beauregard",
    lastName: "Cuffley",
    dateOfBirth: "26/9/1971",
    startDate: "27/3/2016",
    street: "4 Raven Trail",
    city: "Dayton",
    zipCode: "45419",
    state: "OH",
    department: "Engineering",
  },
  {
    firstName: "Gard",
    lastName: "Boor",
    dateOfBirth: "22/10/1965",
    startDate: "2/2/2021",
    street: "18 Fairfield Avenue",
    city: "Washington",
    zipCode: "20062",
    state: "DC",
    department: "Marketing",
  },
  {
    firstName: "Xaviera",
    lastName: "Bollans",
    dateOfBirth: "1/10/1963",
    startDate: "6/3/2019",
    street: "432 Tennessee Crossing",
    city: "Phoenix",
    zipCode: "85030",
    state: "AZ",
    department: "Engineering",
  },
  {
    firstName: "Pauly",
    lastName: "Domesday",
    dateOfBirth: "22/1/1996",
    startDate: "18/11/2016",
    street: "848 Butterfield Way",
    city: "Memphis",
    zipCode: "38168",
    state: "TN",
    department: "Engineering",
  },
  {
    firstName: "Patten",
    lastName: "Cartman",
    dateOfBirth: "22/4/1998",
    startDate: "17/12/2012",
    street: "2 Comanche Junction",
    city: "Fort Wayne",
    zipCode: "46896",
    state: "IN",
    department: "Marketing",
  },
  {
    firstName: "Payton",
    lastName: "Dogg",
    dateOfBirth: "4/7/1976",
    startDate: "26/7/2021",
    street: "2644 8th Plaza",
    city: "Midland",
    zipCode: "48670",
    state: "MI",
    department: "Sales",
  },
  {
    firstName: "Innis",
    lastName: "Gooderson",
    dateOfBirth: "28/10/2000",
    startDate: "13/6/2007",
    street: "371 Sycamore Court",
    city: "Greenville",
    zipCode: "29605",
    state: "SC",
    department: "Human Resources",
  },
  {
    firstName: "Joane",
    lastName: "Swatridge",
    dateOfBirth: "2/12/1995",
    startDate: "1/12/2020",
    street: "08853 Waubesa Avenue",
    city: "Peoria",
    zipCode: "61656",
    state: "IL",
    department: "Human Resources",
  },
  {
    firstName: "Richardo",
    lastName: "McFarlane",
    dateOfBirth: "15/7/1969",
    startDate: "12/7/2003",
    street: "193 Summer Ridge Pass",
    city: "Midland",
    zipCode: "79710",
    state: "TX",
    department: "Sales",
  },
  {
    firstName: "Elnore",
    lastName: "Alexander",
    dateOfBirth: "27/8/1988",
    startDate: "7/1/2015",
    street: "2 Del Sol Circle",
    city: "Santa Ana",
    zipCode: "92705",
    state: "CA",
    department: "Sales",
  },
  {
    firstName: "Christie",
    lastName: "Bernade",
    dateOfBirth: "2/3/1987",
    startDate: "21/11/2006",
    street: "6679 Bayside Point",
    city: "Shawnee Mission",
    zipCode: "66225",
    state: "KS",
    department: "Marketing",
  },
  {
    firstName: "Damian",
    lastName: "Georgelin",
    dateOfBirth: "2/8/1989",
    startDate: "23/8/2004",
    street: "2074 Monica Pass",
    city: "Little Rock",
    zipCode: "72209",
    state: "AR",
    department: "Marketing",
  },
  {
    firstName: "Olav",
    lastName: "Golson",
    dateOfBirth: "27/7/1967",
    startDate: "23/9/2013",
    street: "301 Forest Road",
    city: "Roanoke",
    zipCode: "24014",
    state: "VA",
    department: "Legal",
  },
  {
    firstName: "Sheila-kathryn",
    lastName: "McGing",
    dateOfBirth: "20/6/1981",
    startDate: "17/2/2020",
    street: "04259 Delaware Plaza",
    city: "Oklahoma City",
    zipCode: "73190",
    state: "OK",
    department: "Marketing",
  },
  {
    firstName: "Nerita",
    lastName: "Pratley",
    dateOfBirth: "27/2/1978",
    startDate: "1/2/2003",
    street: "51504 Nancy Place",
    city: "Louisville",
    zipCode: "40225",
    state: "KY",
    department: "Human Resources",
  },
  {
    firstName: "Hermon",
    lastName: "Coite",
    dateOfBirth: "6/9/1991",
    startDate: "29/5/2013",
    street: "077 Susan Parkway",
    city: "Humble",
    zipCode: "77346",
    state: "TX",
    department: "Human Resources",
  },
  {
    firstName: "Colette",
    lastName: "Wilmott",
    dateOfBirth: "28/12/1952",
    startDate: "19/2/2011",
    street: "07 Dorton Place",
    city: "Richmond",
    zipCode: "23237",
    state: "VA",
    department: "Human Resources",
  },
  {
    firstName: "Fae",
    lastName: "Ravenshaw",
    dateOfBirth: "7/11/1979",
    startDate: "9/1/2022",
    street: "83 Westport Plaza",
    city: "Minneapolis",
    zipCode: "55470",
    state: "MN",
    department: "Engineering",
  },
  {
    firstName: "Woody",
    lastName: "Brasted",
    dateOfBirth: "26/10/1954",
    startDate: "29/5/2021",
    street: "80102 Reindahl Road",
    city: "Kansas City",
    zipCode: "64109",
    state: "MO",
    department: "Human Resources",
  },
  {
    firstName: "Elvera",
    lastName: "Bougourd",
    dateOfBirth: "27/6/1978",
    startDate: "20/12/2021",
    street: "25 Sheridan Center",
    city: "Vero Beach",
    zipCode: "32964",
    state: "FL",
    department: "Legal",
  },
  {
    firstName: "Paolo",
    lastName: "Raye",
    dateOfBirth: "31/10/1983",
    startDate: "17/8/2000",
    street: "13 Warrior Drive",
    city: "Norfolk",
    zipCode: "23520",
    state: "VA",
    department: "Legal",
  },
  {
    firstName: "Blanch",
    lastName: "Scholard",
    dateOfBirth: "16/4/1992",
    startDate: "7/12/2001",
    street: "72 Kedzie Alley",
    city: "Washington",
    zipCode: "20525",
    state: "DC",
    department: "Sales",
  },
  {
    firstName: "Mahalia",
    lastName: "Grabban",
    dateOfBirth: "22/11/1987",
    startDate: "17/1/2022",
    street: "31694 Gerald Parkway",
    city: "Cincinnati",
    zipCode: "45271",
    state: "OH",
    department: "Legal",
  },
  {
    firstName: "Gwenny",
    lastName: "Lopez",
    dateOfBirth: "25/4/1953",
    startDate: "20/7/2016",
    street: "2554 Mitchell Point",
    city: "Little Rock",
    zipCode: "72209",
    state: "AR",
    department: "Engineering",
  },
];
