import * as React from "react";
import { useState } from "react";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import logo from "./logo_HRnet.jpeg";
import { makeStyles } from "@material-ui/core";
import { Tabs, Tab } from "@mui/material";
import { Link, useLocation } from "react-router-dom";
import { useEffect } from "react";

/**
 * @description Styles for the `DesktopNav` component.
 */
const useStyles = makeStyles({
  tabs: {
    "& .MuiTabs-indicator": {
      backgroundColor: "#4C6306",
      height: 3,
    },
    "& .MuiTab-root.Mui-selected": {
      // backgroundColor: "green",
      color: "#4C6306",
    },
  },
});

/**
 * @description An array of objects representing the links in the navigation bar.
 *
 * @type {Object[]}
 */
const links = [
  {
    label: "Create Employee",
    path: "/",
  },
  {
    label: "View Current Employees",
    path: "/employee-list",
  },
];

/**
 * @description A navigation bar for desktop screens.
 *
 * @param {number} tabValue - The value of the currently selected tab.
 * @param {function(number)} setTabValue - A function to set the value of the selected tab.
 * @param {Location} location - The location object from the `react-router-dom` package, representing the current URL.
 * @param {Object} classes - The classes object generated by the `makeStyles` function from `@material-ui/core`, containing the styles for the component.
 * @returns {React.Component} The rendered desktop navigation menu.
 *
 */
function DesktopNav() {
  const [tabValue, setTabValue] = useState(0);
  const location = useLocation();
  const classes = useStyles();

  useEffect(() => {
    setTabValue(links.findIndex((link) => link.path === location.pathname));
  }, [location.pathname]);

  /**
   * @description Handles the change event emitted by the tabs component when the selected tab changes.
   *
   * @param {React.ChangeEvent<{}>} event - The change event emitted by the tabs component.
   * @param {number} newValue - The new value of the selected tab.
   */
  const handleChange = (event, newValue) => {
    setTabValue(newValue);
  };

  return (
    <>
      <Box
        aria-label="HRnet logo"
        sx={{
          flexGrow: 1,
          alignItems: "center",
          display: { xs: "none", md: "flex" },
        }}
      >
        <Box component={Link} to="/">
          <Box
            component="img"
            sx={{
              mx: 1.5,
              height: 65,
              marginTop: 0.5,
            }}
            alt="HRnet logo"
            src={logo}
          />
        </Box>

        <Typography
          aria-label="HRnet"
          component={Link}
          label="Home"
          to="/"
          variant="h6"
          noWrap
          sx={{
            mr: 2,
            flexGrow: 1,
            display: { xs: "none", md: "flex" },
            fontFamily: "monospace",
            fontWeight: 700,
            letterSpacing: ".3rem",
            color: "#4C6306",
            textDecoration: "none",
          }}
        >
          HRnet
        </Typography>
        <Box>
          <Tabs
            value={tabValue}
            className={classes.tabs}
            onChange={handleChange}
            aria-label="NavigationTab"
          >
            {links.map(({ label, path }) => (
              <Tab
                key={label}
                label={label}
                component={Link}
                to={path}
                sx={{
                  display: "block",
                  py: 4,
                }}
              />
            ))}
          </Tabs>
        </Box>
      </Box>
    </>
  );
}
export default DesktopNav;
